spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/immoc_db?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka
env: dev
